FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel
# Install necessary dependencies and fix repository issues for libsndfile1-dev
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    make \
    libssl-dev \
    gcc \
    sudo \
    bash \
    software-properties-common \
    && add-apt-repository universe \
    && apt-get update \
    && apt-get install -y libsndfile1-dev \
    && rm -rf /var/lib/apt/lists/*

# RUN python -m unidic download

WORKDIR /app/tts_services/
RUN rm -rf TTS
RUN git clone -b add-vietnamese-xtts https://github.com/thinhlpg/TTS.git

WORKDIR /app/tts_services/TTS/
RUN make system-deps
RUN make install

WORKDIR /app/tts_services/
# Install Python dependencies
RUN pip3 install fugashi[unidic-lite] fugashi[unidic]
RUN python3 -m unidic download

RUN pip3 install --upgrade pip
COPY requirements-vi.txt requirements-vi.txt
RUN python3 -m pip install --default-timeout=90000 -r /app/tts_services/requirements-vi.txt


COPY . /app/tts_services/

CMD [ "sh", "./script/start_services_vi.sh" ]
